services:
  mosquitto:
    image: eclipse-mosquitto:2.0.21 ## Version of mosquitto to use
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9090:9090"
    volumes:
      - ../configs:/mosquitto/config/:ro
      - ../configs/blcert.pem:/mosquitto/printer/blcert.pem:ro
