---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mosquitto-printer
  namespace: homeautomation
spec:
  secretName: mosquitto-printer-ssl
  commonName: &hostname "printer-relay.EXAMPLE.COM" ## Hostname for the MQTT relay certificate
  dnsNames:
    - *hostname
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer